Servicio User y Recetas
Standar-sazon/api_standar_sazon pull request #13
Opened 2021-02-22 05:37 UTC by Silver899

2021-02-23 01:36 UTC, EveFer commented on src/usecases/recipes.js
> +    if (idUser) {
Ojo @Silver899  Aqui validas si se envia un idUser, 

Vericar Validación

2021-02-23 01:36 UTC, EveFer commented on src/routes/recipes.js
> +    const recipesByUser = await recipes.getAll(user)
@Silver899 Veo que cambiaste el nombre de tu función getAll() a getByUser(), entonces ya no deberías llamar a getAll()

2021-02-23 01:36 UTC, EveFer commented on src/routes/recipes.js
@Silver899  Creaste otro endpoint?

2021-02-23 01:38 UTC, Silver899 commented on src/routes/recipes.js
Si, creo que tenía que reemplazar el otro pero lo dude, entonces deje dos :(

2021-02-23 01:39 UTC, Silver899 commented on src/routes/recipes.js
> +    const recipesByUser = await recipes.getAll(user)
Yes, justo lo acabo de cambiar a getByUser jeje

2021-02-23 02:27 UTC, EveFer requested changes

2021-02-23 02:27 UTC, EveFer commented on src/usecases/recipes.js
> +    if (idUser) {
Si el idUser es null, es decir, que no venga en el request retornara todas la recetas va.

```suggestion
    if (!idUser) {
```

2021-02-23 04:57 UTC, EveFer approved these changes

2021-02-23 06:53 UTC, arce2508 commented
OK

2021-02-23 06:54 UTC, arce2508 approved these changes

2021-02-23 06:55 UTC, arce2508 commented
listo!

2021-02-23 06:55 UTC, arce2508 commented
OK

2021-02-23 06:55 UTC, arce2508 commented
OK

2021-02-24 02:15 UTC, EveFer approved these changes

2021-02-24 02:16 UTC, merged