[CREATION] Main Recipe model
Standar-sazon/api_standar_sazon pull request #5
Opened 2021-02-12 22:12 UTC by TruEric

Modelo de receta principal creado

2021-02-12 22:54 UTC, arce2508 requested changes
Hola, Eric!

Solo vi en tu Schema que para hacer el ref en SubRecetas, ha que ponerlo en plural. 
Es decir: 

ref: 'SubRecipes' 

por favor.

2021-02-13 00:30 UTC, TruEric commented
Listo Arce, ya está corregido.

2021-02-13 01:35 UTC, arce2508 commented
Gracias, Eric!

2021-02-13 05:46 UTC, EveFer commented on src/models/recipes.js
> +})
```suggestion
},{
    timestamp: true
} )
```

2021-02-13 05:52 UTC, EveFer approved these changes

2021-02-13 06:56 UTC, EveFer approved these changes

2021-02-13 06:57 UTC, arce2508 approved these changes

2021-02-13 06:57 UTC, merged